version: '3.1'
services:
  webserver:
    build: .
    image: myphp:1
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html/
    environment:
      XDEBUG_CONFIG: remotehost=host.docker.internal

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  myadmin:
      image: phpmyadmin
      restart: always
      ports:
        - 8080:80
      depends_on:
        - db